@server = http://localhost:4004/odata/v4/embedding-storage


### update books
# @name update_book
PATCH {{server}}/Books(ID = 271)
Content-Type: application/json

{
    "title":"Catweazle",
     "descr":"Catweazle is a British fantasy television series, starring Geoffrey Bayldon in the title role, and created by Richard Carpenter for London Weekend Television. The first series, produced and directed by Quentin Lawrence, was screened in the UK on ITV in 1970. The second series, directed by David Reid and David Lane, was shown in 1971. Each series had thirteen episodes, most but not all written by Carpenter, who also published two books based on the scripts."
}

### Similarity Search
# @name similarity_search
@query = describe me the British television series Catweazle
GET {{server}}/Search(query='{{query}}')/Set